include:
  - project: ultimaker/stardust/print-cluster-jedi-scripts
    file: /gitlab/gitlab-ci-template.yml

variables:
  GIT_AUTHOR_NAME: embedded
  GIT_AUTHOR_EMAIL: embedded@ultimaker.com
  GIT_COMMITTER_NAME: embedded
  GIT_COMMITTER_EMAIL: embedded@ultimaker.com
  EMAIL: embedded@ultimaker.com

stages:
  - validate
  - test
  - build
  - release

validate:
  stage: validate
  image: python:3.7.2-slim
  script:
    - python -m pip install lxml==4.3.0
    - python scripts/check_material_profiles_new_with_lxml.py
  tags:
    - docker
